# Site settings
title: 'Ian Tabolt'
description:
  Hello! I'm a software engieer at Foursquare where I work on our
  developer platform team, which builds our APIs
  that make external developers&apos; lives easier
  by providing Foursquare's own location technology for use in their apps.
  <br/>
  Previously I was on the developer systems team, where I worked to make
  our own developers&apos; lives easier with awesome Scala tooling and build
  workflows.
  <br/>
  Aside from being a professional Scala enthusiast, I am also a
  stubborn bike commutor, an okay marathon runner, Yankees & Ravens fan,
  and husband / 2x doggie dad / 1x baby dad.
url: 'iantabolt.com'
baseurl: ''
disqus_shortname: 'tabo'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Ian Tabolt'
  email: ian@tabo.lt
  twitter_username: iantabolt
  # facebook_username: ian.tabolt
  foursquare_username: iantabolt
  github_username: iantabolt
  linkedin_username: iantabolt

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor']
